### ISSUE TITLE
error executing query: invalid term frequency key, empty docid

### ISSUE THREAD

**Issue by jvermillard** [blevesearch/bleve-hosted#2] opened 2015-09-28 19:45 UTC
testing my brand new hugoidx search index.

work if no hit:

```
 curl http://localhost:8080/api/search.bleve/_search -d '{"query":{"query":"mqttz"}}'
{"request":{"query":{"query":"mqttz","boost":1},"size":0,"from":0,"highlight":null,"fields":null,"facets":null,"explain":false},"hits":[],"total_hits":0,"max_score":0,"took":162462,"facets":{}}
```

but if I have a hit:

```
curl http://localhost:8080/api/search.bleve/_search -d '{"query":{"query":"mqtt"}}' 
error executing query: invalid term frequency key, empty docid
```

**Comment by mschoch** [comment] 2015-09-28 19:51
I'm not able to reproduce this problem.  Is it possible to make the index available?

**Comment by jvermillard** [comment] 2015-09-28 19:52
yes, let me upload that somewhere

**Comment by jvermillard** [comment] 2015-09-28 19:56
https://drive.google.com/file/d/0B_sCue57JQOrSEVsTEY4ZWV1UFk/view?usp=sharing

**Comment by mschoch** [comment] 2015-09-28 20:34
Thanks, the index definitely contains an invalid row.  I need to track down how that happened.

Can you confirm you get this same problem when you build a new index from scratch with the latest hugoidx?

**Comment by jvermillard** [comment] 2015-09-28 20:39
same issue after go get -u github.com/blevesearch/hugoidx

**Comment by mschoch** [comment] 2015-09-28 20:46
OK, I've confirmed that bleve allows you to index a document with an empty ID.  This leads to an invalid row in the index, as at that layer we expect the doc ID must be non-empty.  So, there are at least 2 problems:
1.  There should be validation somewhere that the ID isn't empty (bleve bug)
2.  Something in hugoidx is trying to index a page with empty ID.

As a quick hack, can you modify hugodix locally, insert some logging before this line:

https://github.com/blevesearch/hugoidx/blob/master/main.go#L69

Something that identifies which page it is, and why the RelPermLink is empty?  That is what we try to use for the doc id.

Meanwhile I'll work on adding the validation to bleve.

**Comment by jvermillard** [comment] 2015-09-28 20:55
thanks for the help, will try that tomorrow!

**Comment by jvermillard** [comment] 2015-09-29 08:25
fixed the issue with 

```
if len(p.Title) <= 0 {
   continue
}
```

**Comment by mschoch** [comment] 2015-09-29 12:18
Since this tool is new, and I'm not a Hugo expert, can you share any information about the title being empty?  Is this a common occurrence in a hugo site?  Are there a class of pages that will all be like this?

**Comment by jvermillard** [comment] 2015-09-30 08:57
we have a bunch of html files we are including in other pages using some ajax calls.

**Comment by mschoch** [comment] 2015-09-30 14:06
Interesting, I was under the impression that Hugo wouldn't consider them pages.  I'll add the length check to hugoidx unless/until we have something better.

**Comment by mschoch** [comment] 2015-09-30 14:12
fixed in hugoidx, https://github.com/blevesearch/hugoidx/commit/c9bdcd240243fba2afaaa578474d508126f79342

**Closed as completed by mschoch** 2015-09-30 14:12 UTC
